coverage:
  ignore: 
    - "tests"
    - "sleap_nn/data/cycler.py"  # Vendored from torchdata.
  status:
    project:  # Measures overall project coverage.
      default: false
      package:
        target: auto
        threshold: 2%  # Less leeway with backend code.
        paths:
          - "sleap_nn/"
        informational: true  # Don't fail PRs on coverage
    patch:  #  Only measures lines adjusted in the pull request.
      default: false
      package:
        target: 95%  # All backend code should be tested...
        paths:
          - "sleap_nn/"
        informational: true  # Don't fail PRs on coverage