name: sleap-nn

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pydantic
  - lightning
  - pytorch
  - torchvision
  - h5py
  - pandas
  - scipy
  - attrs
  - opencv
  - ffmpeg<6.1.0
  - imageio
  - imageio-ffmpeg
  - av
  - omegaconf
  - wandb
  - ffmpeg
  - kornia
  - matplotlib
  - pynwb
  - ndx-pose
  - pip
  - pip:
    - "--editable=.[dev]"