name: sleap-nn

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch
  - pydantic<=2.0
  - lightning=2.0.5 # due to dependency conflict Lightning Issue (#18027)
  - cpuonly
  - kornia
  - torchvision
  - imageio
  - av
  - ffmpeg
  - matplotlib
  - pip
  - pip:
    - "--editable=.[dev]"