name: sleap-nn

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch-cuda=11.8
  - pydantic<2.0
  - lightning=2.0.5 # due to dependency conflict Lightning Issue (#18027)
  - cudnn
  - pytorch
  - torchvision
  - torchdata
  - imageio
  - av
  - ffmpeg
  - kornia
  - matplotlib
  - pip
  - pip:
    - "--editable=.[dev]"