name: sleap-nn

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - pydantic
  - lightning
  - pytorch
  - torchvision
  - h5py
  - pandas
  - simplejson
  - scipy
  - attrs
  - opencv
  - ffmpeg
  - imageio
  - imageio-ffmpeg >=0.5.0
  - av
  - omegaconf
  - wandb
  - ffmpeg
  - kornia
  - matplotlib
  - sleap-io
  - rich
  - pynwb
  - ndx-pose<0.2.0
  - pip
  - pip:
    - "--editable=.[dev]"
    - litdata