name: sleap-nn

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - sleap-io>=0.2.0
  - pydantic
  - h5py
  - pandas
  - jsonpickle
  - simplejson
  - scipy
  - attrs
  - ffmpeg
  - opencv
  - imageio
  - pyzmq
  - av
  - omegaconf
  - wandb
  - kornia
  - matplotlib
  - seaborn
  - rich
  - pynwb
  - pillow
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - "--editable=.[dev]"
    - torch
    - torchvision
    - lightning
    - litdata
    - hydra-core
    - loguru
