name: sleap-nn

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch
  - lightning=2.0.1
  - cpuonly
  - torchdata
  - torchvision
  - imageio
  - av
  - ffmpeg
  - albumentations
  - matplotlib
  - pip
  - pip:
    - "--editable=.[dev]"