name: sleap-nn

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - sleap-io>=0.2.0
  - pydantic
  - lightning
  - pytorch
  - torchvision
  - h5py
  - pandas
  - jsonpickle
  - scipy
  - attrs
  - ffmpeg
  - opencv
  - imageio
  - pyzmq
  - av
  - omegaconf
  - wandb
  - kornia
  - matplotlib
  - seaborn
  - rich
  - pynwb
  - pip
  - pip:
    - "--editable=.[dev]"
    - hydra-core
    - loguru
