name: sleap-nn

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - sleap-io>=0.2.0
  - pytorch
  - pydantic
  - lightning
  - cpuonly
  - torchvision
  - h5py
  - pandas
  - simplejson
  - scipy
  - attrs
  - ffmpeg
  - opencv
  - imageio
  - av
  - omegaconf
  - wandb
  - kornia
  - matplotlib
  - rich
  - pynwb
  - pip
  - pip:
    - "--editable=.[dev]"
    - litdata
    - hydra-core
    - loguru
