# Root config for sleap-nn-train
defaults:
  - _self_
  - override hydra/help: training_help

# You can leave the rest empty so Hydra has a struct to work with.
# This prevents `{}` from being passed down.
model_config: {}
trainer_config: {}
data_config: {}
