dataset_mapper:
  0: dataset_1
  1: dataset_2
  2: dataset_3
data_config:
  provider: LabelsReader
  train_labels_path: 
    0: minimal_instance.pkg.slp
    1: minimal_instance.pkg.slp
    2: minimal_instance.pkg.slp
  val_labels_path:
    0: minimal_instance.pkg.slp
    1: minimal_instance.pkg.slp
    2: minimal_instance.pkg.slp
  test_file_path:
    0: minimal_instance.pkg.slp
    1: minimal_instance.pkg.slp
    2: minimal_instance.pkg.slp
  data_pipeline_fw: torch_dataset_cache_img_disk # one of `torch_dataset`, `torch_dataset_cache_img_memory`, `torch_dataset_cache_img_disk`
  cache_img_path: ./img_dir/
  use_existing_imgs:
    0:
    1:
    2:
  user_instances_only: True
  litdata_chunks_path:
  chunk_size:
  delete_cache_imgs_after_training:
  preprocessing:
    max_width: 
      0:
      1:
      2:
    max_height: 
      0:
      1:
      2:
    scale:
      0:
      1:
      2:
    is_rgb: True
    crop_hw:
      0:
      1:
      2:
    min_crop_size:
  use_augmentations_train: true
  augmentation_config:
    geometric:
      rotation: 180.0
      scale: null
      translate_width: 0
      translate_height: 0
      affine_p: 0.5

model_config:
  init_weights: xavier
  pre_trained_weights:
  pretrained_backbone_weights:
  pretrained_head_weights:
  backbone_type: unet
  dataset_loss_weights:
    0: 1.0
    1: 1.0
    2: 1.0
  keypoint_mining:
    online_mining: False
    hard_to_easy_ratio: 2.0
    min_hard_keypoints: 2
    max_hard_keypoints:
    loss_scale:
  backbone_config:
      in_channels: 1
      kernel_size: 3
      filters: 16
      filters_rate: 2
      max_stride: 16
      convs_per_block: 2
      stacks: 1
      stem_stride: 
      middle_block: True
      up_interpolate: True
  head_configs:
    single_instance:
    centroid:
    bottomup:
    centered_instance:
      fitbbox: False # False: centroid crop, True: crop with fit bbox
      confmaps:
        0: 
          part_names:
          anchor_part: 0
          sigma: 1.5
          output_stride: 2
        1: 
          part_names:
          anchor_part: 2
          sigma: 1.5
          output_stride: 2
        2: 
          part_names:
          anchor_part: 4
          sigma: 1.5
          output_stride: 2
trainer_config:
  train_data_loader:
    batch_size: 4
    shuffle: true
    num_workers: 2
  val_data_loader:
    batch_size: 4
    num_workers: 2
  combined_loader_mode: "max_size_cycle" # or "min_size", "max_size"
  model_ckpt:
    save_top_k: 1
    save_last: true
  trainer_devices: 1
  trainer_accelerator: gpu
  profiler: simple
  trainer_strategy: "ddp_find_unused_parameters_false" # "auto", "ddp", "ddp_find_unused_parameters_true"
  enable_progress_bar: false
  log_inf_epochs: 5
  steps_per_epoch: 
    0:
    1:
    2:
  max_epochs: 10
  seed: 1000
  use_wandb: true
  wandb:
    entity:
    project: 'test_centroid_centered'
    name: 'fly_unet_centered'
    wandb_mode: ''
    api_key: ''
    prv_runid:
    group:
  save_ckpt: true
  save_ckpt_path: 'multi_head'
  resume_ckpt_path:
  optimizer_name: Adam
  optimizer:
    lr: 0.0001
    amsgrad: false
  lr_scheduler:
    scheduler: ReduceLROnPlateau
    reduce_lr_on_plateau:
      threshold: 1.0e-07
      threshold_mode: abs
      cooldown: 3
      patience: 5
      factor: 0.5
      min_lr: 1.0e-08
  early_stopping:
    stop_training_on_plateau: True
    min_delta: 1.0e-08
    patience: 20